### PR TITLE
:arrow_up: django-treebeard 3.0 compatibility

### PR DESCRIPTION
**Pull request by nikolas**
Treebeard 3.0 fixes some method deprecation warnings.

### CODE REVIEW

**Comment by thraxil** [comment]
Have we tested this with any full pagetree apps yet? It's good to see that there's finally a new treebeard release out, but updates in the past have been non-trivial. And is there backwards compatibility on `movenodeform_factory`? Ie, if someone pulls in this version of pagetree will it force them to upgrade treebeard as well?

**Comment by nikolas** [comment]
`movenodeform_factory` is in Treebeard 2.0. I was testing my new `movenodeform_factory` pagetree code with treebeard 2.0 on worth, and it's not behaving correctly - I can't actually move the nodes. I'll update this PR when I sort out the issue.

**Comment by sdreher** [comment]
How do we feel about the workflow in a situation like this. Should the PR be closed? Or, can we indicate clearly that it's not ready to go? I'm not sure comments are enough.

**Comment by nikolas** [comment]
I'm fine with closing the PR until the branch is ready, or we could agree on putting something like "WIP" in the title, for work-in-progress pull requests like this that aren't ready to merge. Doesn't really matter to me.

**Comment by thraxil** [comment]
So far, I feel like the context and status has generally been pretty clear. I think it's up to the person who opens the PR whether they want to withdraw it or keep it open while they work on it. In the latter case putting WIP or just being clear in a comment that it's not really ready to merge is fine. Whoever merges the PR has the responsibility of understanding the status of the discussion and probably shouldn't merge if there are unresolved questions.

**Comment by nikolas** [comment]
I've resolved the issue I was having - I wasn't passing in the `instance` arg at the right time.

I've tested the new `MoveNodeForm` that uses `movenodeform_factory` with worth using Treebeard 2.0, so this should be fine to merge.

**Pull request merged**
